# Generated by Django 2.2.13 on 2022-01-21 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmembership',
            old_name='member',
            new_name='user',
        ),
    ]
