# Generated by Django 2.2.13 on 2022-01-21 15:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20220121_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default=uuid.uuid1, max_length=100, unique=True),
        ),
    ]
