# Generated by Django 2.2.13 on 2021-06-17 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_project_space'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('labels', models.CharField(max_length=120)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('assignee', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_assignee', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
                ('reporter', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_reporter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
