# Generated by Django 2.2.26 on 2022-02-05 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_project_description"),
        ("projects", "0002_auto_20220205_1142"),
    ]

    operations = []
