# Generated by Django 2.2.13 on 2022-02-07 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_board_column_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="board_owner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
