# Generated by Django 2.2.26 on 2022-02-07 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_auto_20220207_1330"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="board",
            name="members",
        ),
        migrations.RemoveField(
            model_name="board",
            name="owner",
        ),
        migrations.AddField(
            model_name="board",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="board_project",
                to="projects.Project",
            ),
            preserve_default=False,
        ),
    ]
