# Generated by Django 2.2.27 on 2022-04-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_risk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risk',
            name='severity',
        ),
        migrations.AlterField(
            model_name='risk',
            name='impact',
            field=models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], max_length=2),
        ),
    ]
