# Generated by Django 2.2.13 on 2021-10-19 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("spaces", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="spacemembership",
            old_name="user",
            new_name="member",
        ),
    ]
