# Generated by Django 2.2.13 on 2021-11-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spaces", "0003_auto_20211019_1343"),
    ]

    operations = [
        migrations.AlterField(
            model_name="space",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
