# Generated by Django 2.2.27 on 2022-04-16 16:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fehler_auth', '0003_auto_20220416_1626'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spaces', '0006_auto_20220416_1625'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='spacemembership',
            unique_together={('space', 'member', 'invite')},
        ),
    ]
