# Generated by Django 2.2.13 on 2021-03-16 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("spaces", "0001_initial"),
        ("fehler_auth", "0002_invite"),
    ]

    operations = [
        migrations.AddField(
            model_name="invite",
            name="space",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="spaces.Space",
            ),
            preserve_default=False,
        ),
    ]
