# Generated by Django 2.2.27 on 2022-04-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fehler_auth', '0002_auto_20211002_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
