# Generated by Django 2.2.27 on 2022-04-16 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0007_auto_20220416_1626'),
        ('fehler_auth', '0003_auto_20220416_1626'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invite',
            unique_together={('space', 'email')},
        ),
    ]
