# Generated by Django 2.2.27 on 2022-03-30 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='column',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='boards.Column'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_due',
            field=models.DateField(blank=True, null=True),
        ),
    ]
