# Generated by Django 2.2.27 on 2022-02-08 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="column",
            name="tasks",
        ),
        migrations.AddField(
            model_name="task",
            name="column",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_column",
                to="board.Column",
            ),
            preserve_default=False,
        ),
    ]
