# Generated by Django 2.2.27 on 2022-02-12 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0008_auto_20220212_0319"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="column",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="board.Column",
            ),
        ),
    ]
